### ISSUE TITLE
Description in composer.json needs to be upgraded to reflect support for Statamic

### ISSUE THREAD

**Issue by architchandra** [mitydigital/statamic-sitemapamic#13]
https://github.com/mitydigital/statamic-sitemapamic/blob/8747f319f322562baeaf459a7c4d9052b9c7e95b/composer.json#L3

Sorry for the really tiny issue. Just noticed it and thought that this would be helpful. :)
This time, maybe [just Statamic](https://statamic.com/blog/statamic-4-unleashed) (without the version number) should be enough.

**Comment by martyf** [comment]
Thanks, I've updated this in the composer.json file. Still referencing 3 as that will be dropped in an upcoming rework of the add-on.
