### ISSUE TITLE
How can I generate sitemap for my other locale?

### ISSUE THREAD

**Issue by barkinmeric** [mitydigital/statamic-sitemapamic#17]
I have a statamic 4.0 project. I have a page collection that has tr and en locales. tr is my default one and its route is site-url.com/ and sitemapamic can automatically generate sitemap for tr locale. But for en locale that has site-url.com/en route, sitemapamic can't generate automatically becaue of that I needed to add en routes to SitemapamicServiceProvider manually but this approach is not viable. Is there any way to make this process automatically?

**Comment by martyf** [comment]
Given family commitments over the holidays, I won't have a chance to look at this until next week some time. Just wanted to let you know I've seen this, and will get back to you as soon as I can.

**Comment by barkinmeric** [comment]
Thank you for your kind reply. I wish you a good holiday with your family. I'm waiting to hear from you. Thanks again :)

**Comment by barkinmeric** [comment]
I just found sitemap.xml for /en site in another route than /sitemap.xml, it was in /en/sitemap.xml 🤦‍♂️
I was reading doc of peak library and then eureka 😂
Thank you for this library. Take care :) 
<img width="628" alt="image" src="https://github.com/mitydigital/statamic-sitemapamic/assets/47567787/1f7271d6-3ea5-4166-90a9-ed95f6c58f42">

**Comment by martyf** [comment]
Glad this got sorted - might need to have a play with Peak and Sitemapamic to see how the two can work together too as this is the second time recently something like this has come up when used in a Peak site.

**Comment by barkinmeric** [comment]
Actually I wasn't using Peak. I was only looking for other sitemap generator to use instead of this package. But in the docs of Peak I found the solution for my problem that I had while using this add-on. Maybe this locale specific sitemap section could be added to the documentation.

**Comment by martyf** [comment]
I've got major updates coming to Sitemapamic and Feedamic that will help with multi-site given there are several ways things can be done. I think I misunderstood your initial issue, sorry.
