### ISSUE TITLE
Route not defined with Dynamic Routes

### ISSUE THREAD

**Issue by MrMooky** [mitydigital/statamic-sitemapamic#26]
### Bug description

I'm using "[Dynamic Routes](https://docs.mity.com.au/sitemapamic/configuration/dynamic-routes)" and just updated a project to Laravel 11 and Statamic 5. This included using the latest version of your package. After the upgrade I get `Route [object.show] not defined`, even though the route still exists is the `web.php` file like that:

`Route::get('/objekt/{object:slug}', [PropertyController::class, 'show'])->name('object.show');`

### Steps to reproduce

Essentially, just follow the steps that are mentioned [here](https://docs.mity.com.au/sitemapamic/configuration/dynamic-routes) in the "Using named routes in a provider" section. This is the code I have in my custom `SitemapServiceProvider`:

```
$this->app->booted(function () {
    $objects = Property::query()
        ->where('is_project', false)
        ->where('is_secret', false)
        ->get();

    $routes = [];

    foreach ($objects as $object) {
        $routes[] = new SitemapamicUrl(
            route('object.show', ['object' => $object]),
            now()->toW3cString()
        );
    }

    Sitemapamic::addDynamicRoutes(function () use ($routes) {
        return $routes;
    });
});
```

### Environment and versions

```yaml
I'm not able to run this, see "Additional details" for screenshot.
```

### Additional details

The error occurs when running any kind of CLI prompt (eg: `php please support:details`) and also when viewing the frontend or backend.

<img width="988" alt="Screenshot 2024-09-30 at 13 22 51" src="https://github.com/user-attachments/assets/f8bcb39c-4c3f-4ab3-9669-5de0c0a28843">

**Comment by martyf** [comment]
Are you using the new Laravel 11 app structure (i.e. the slim `bootstrap/app.php` file), or the older app structure?

It sounds to me like your `SitemapServiceProvider` is being called before the routes are loaded by Laravel. I'd love more detail so that I can try to be able to reliably replicate what you're seeing at my end.

**Comment by martyf** [comment]
Also, if you remove your service provider (for the add-on's dynamic routes), if you run `php artisan route:list` do you see your `object.show` route in the list?

**Comment by MrMooky** [comment]
Yes, I upgraded with LaravelShift and that also switched to the slim structure. When removing the foreach loop where the route is called (as seen in the code example in my initial post), I can see the route in the list.

<img width="387" alt="Screenshot 2024-10-01 at 12 56 38" src="https://github.com/user-attachments/assets/0dcbe544-6acd-4504-b137-8d7d658654cd">

My custom provider is registered in the `providers.php` file at the last position, like this:

```
return [
    App\Providers\AppServiceProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\HorizonServiceProvider::class,
    App\Providers\SitemapServiceProvider::class,
];
```

**Comment by martyf** [comment]
I can replicate this and have worked around it for an existing project (non-Statamic) but can't find the right magic code that did it (its routing was a bit different).

For the meantime you'll need to not use named routes - just looking more in to the boot order of things to try to put my finger on this one.

**Comment by martyf** [comment]
Righto so solution. The `route` helper won't work as expected in the Service Provider because routes may not be registered yet.

However, if you call a named route inside the `addDynamicRoutes` callback, it should work. Here's a rough draft - without your full code can't do a faithful test, so may need to tweak:
```php
Sitemapamic::addDynamicRoutes(function () {
    $objects = Property::query()
        ->where('is_project', false)
        ->where('is_secret', false)
        ->get();

    $routes = [];

    foreach ($objects as $object) {
        $routes[] = new SitemapamicUrl(
            route('object.show', ['object' => $object]),
            now()->toW3cString()
        );
    }

    return $routes;
});
```

The gist here is that the `route` helper is called _within_ the callback, not in the Service Provider itself.

**Comment by MrMooky** [comment]
That works, thanks. I can also remove the `$this->app->booted(function () { ...` (as stated in the docs) line now and it still works. I guess this issue can be closed now and wasn't really an issue with the addon, but just the way I implemented it.

**Comment by martyf** [comment]
No worries at all - just a small little gotcha as to placement but glad it is sorted 👍
