### ISSUE TITLE
Addon is shows as unlisted in Statamic

### ISSUE THREAD

**Issue by jacksleight** [mitydigital/statamic-sitemapamic#4]
Not sure if you were aware but Sitemapamic is appearing as unlisted in the Statamic addons list:

![Screenshot 2022-06-09 at 15 43 14](https://user-images.githubusercontent.com/126740/172875457-8601f498-063b-41de-b681-973c4744f63c.png)

I had the same thing with one of my addons and it was because I hadn't set a "MINIMUM GIT VERSION" in the Marketplace settings. Might be the same issue?

**Comment by martyf** [comment]
Oh that's brilliant - that has solved the issue. There's an open issue with Statamic and Jason was looking in to it, but this has resolved it for me (with a `composer dump-autoload` too). I'll let the Statamic team know about this too.
