### ISSUE TITLE
Any way to use with SSG?

### ISSUE THREAD

**Issue by michaelmannucci** [mitydigital/statamic-sitemapamic#5]
Is there anyway to use this with Statamic SSG to deploy to Netlify?

**Comment by martyf** [comment]
Closed due to inactivity.

**Comment by architchandra** [comment]
This worked for me. Fantastic!

**Comment by martyf** [comment]
Thanks for the note @architchandra: I've added some info about SSG to the docs for both Sitemapamic and Feedamic, as this applies to both.
