### ISSUE TITLE
syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by yabdab** [mitydigital/statamic-sitemapamic#6]
Getting this error when visiting sitemap.xml...

```syntax error, unexpected 'public' (T_PUBLIC), expecting variable (T_VARIABLE)```

https://flareapp.io/share/87nlaxem

**Comment by martyf** [comment]
This addon requires PHP 8 and above as it uses named arguments for the constructor. You're running 7.4. Check your PHP version, and give it another try.

**Comment by yabdab** [comment]
Thanks @martyf . I am using SEO Pro now, so I will remember this if I ever decide to use it again.
