### ISSUE TITLE
Add PHP version constraint to composer.json

### ISSUE THREAD

**Issue by duncanmcclean** [mitydigital/statamic-sitemapamic#8]
### Bug description

I tried to install this the other day in a project using Statamic 3.3 and PHP 7.4 (because we've not got round to updating yet).

After 'composer requiring', I was greeted by some errors because I'm using an older version of PHP than what this addon supports (fair enough - it's my bad for using an older PHP version).

Just a suggestion but it might be worth adding a [PHP version constraint](https://github.com/duncanmcclean/runway/blob/2.x/composer.json#L31) to the `composer.json` file so even if you try to install on an older PHP version, it won't actually let you install.

### Steps to reproduce

Install this addon on a Statamic site running PHP 7.4

### Environment and versions

```yaml
n/a
```

**Comment by martyf** [comment]
Thanks Duncan, I've updated this (and all other addons that were missing a PHP requirement).
